apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template
spec:
  selector:
    matchLabels:
      app: go-template
  template:
    metadata:
      labels:
        app: go-template
    spec:
      containers:
        - name: go-template
          image: asia-southeast1-docker.pkg.dev/playground-364310/go-template/go-template:latest
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - -addr=:8080
            initialDelaySeconds: 180
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - -addr=:8080
            initialDelaySeconds: 180
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 60
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gcr-json-key